services:
  postgres:
    image: postgres:16
    container_name: teleorderx-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: teleorderx
      POSTGRES_USER: teleorderx_user
      POSTGRES_PASSWORD: teleorderx_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: